// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vdutbqrngozppbtjwiwq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZkdXRicXJuZ296cHBidGp3aXdxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYyNDI0NTQsImV4cCI6MjA3MTgxODQ1NH0.a2hzVnNapKzkvv4LrBNuAeUOVefUKXXN_VHi03w81vQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});